In [41]:
import numpy as np

sigA=np.array ( [ [  4,  -2 ],
                  [  1,  1 ],
                   ])

print(sigA)

[[ 4 -2]
 [ 1  1]]


In [42]:
L,v = np.linalg.eig(sigA)

print('Eigenvalues:')
print(L)
print()
print('Eigenvectors:')
print(v)


Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [43]:
#v = v.T  # Transpose the vectors if needed
#for vi in v:
  #  print(np.round(vi,3))

In [44]:
vx = v[:, 0].reshape(2, 1) # Extract the first eigenvector and ensure it's a column vector
print(vx)

[[0.89442719]
 [0.4472136 ]]


In [45]:
# Compute sigA * vx
result = np.dot(sigA, vx)
print(result)

[[2.68328157]
 [1.34164079]]


In [46]:
2.68328157/3  # Confirms that the result is just the values of the eigenvector divided by the first eigenvalue

0.89442719

In [47]:
1.34164079/3

0.44721359666666666

In [48]:
# Convert result to a flat 1D vector
correct_result = result.flatten()

# Print the result
print(correct_result)

[2.68328157 1.34164079]
