## Ejemplo de Graficación de Vectores en 3-D

In [12]:
# Plotting a 3D vector from https://discourse.julialang.org/t/plot-3d-vector-field/2117/2
# Pkg.add("PyPlot")
ENV["PYTHON"] = ""  

""

In [13]:
using PyPlot

In [14]:
pygui(true)  # si se pone verdadero (true) se grafica en una ventana externa con GUIS y se puede rotar, 
             # falso (false) pone la gráfica en una línea siguiente

true

In [23]:
fig = figure()
#ax = fig[:gca]

N = 10
x,y,z,u,v,w = [randn(N) for i in 1:6]  # creamos 10 vectores aleatorios
#z = z/4


6-element Array{Array{Float64,1},1}:
 [0.578388, -1.2378, -0.356011, -0.3565, -1.49092, -0.748104, 1.74181, -1.06256, -0.823306, 0.0445061]      
 [0.389055, -0.969275, 0.918467, 0.869351, -1.91836, 0.0481208, -0.679387, -0.299784, -2.34664, -0.489825]  
 [2.71506, 1.09198, -0.197594, -0.152802, -1.66561, -1.4256, -0.51507, -0.810114, -1.33307, 0.803452]       
 [0.370396, -0.997358, -1.02773, -0.884841, -1.50362, 0.969794, 1.13833, 2.08618, 1.34304, 0.0508885]       
 [0.160082, 0.209857, 0.750425, 0.0349448, 1.48211, 0.746672, 0.581531, 1.2078, 1.20058, 1.13832]           
 [0.667515, -0.0442909, 0.0866367, -0.151029, 0.0140627, -0.189368, 2.68642, -0.813921, -0.96062, 0.0575188]

In [24]:
#ax[:quiver](x,y,z, u,v, w, lw =1.5)
  
xlim([-3.0, 3.0])
ylim([-3.0, 3.0])
zlim([-3.0, 3.0])

quiver(x,y,z, u,v, w, lw =0.5) # grafica los vectores en 3D, los ejes se pueden rotar interactivamente.

# si no funciona se puede usar
#ax[:set_xlim]([0,3])
#ax[:set_ylim]([0,3])
#ax[:set_zlim]([0,3])

PyObject <mpl_toolkits.mplot3d.art3d.Line3DCollection object at 0x14a4e0390>

In [17]:
x

3-element Array{Float64,1}:
 -1.2304563452959387
  2.0235273010394703
  1.2085486738567535

In [18]:
y

3-element Array{Float64,1}:
 1.9839901505660311
 0.7255842255849367
 0.5569370016035591

In [19]:
w

3-element Array{Float64,1}:
  0.2398131714866754
  0.7872746939412101
 -1.060724485896114 

### Graficando vectores unitarios

In [20]:
x = [0;0;0]; y = [0;0;0]; z = [0;0;0]; u = [1;0;0]; v = [0;1;0]; w = [0;0;1]; 

In [21]:
fig = figure()
ax = fig[:gca](projection="3d")
ax[:quiver](x,y,z, u,v, w)
xlim([-0.0, 1.5])
ylim([-0.0, 1.5])
zlim([-0.0, 1.5])

┌ Warning: `getindex(f::Figure, x)` is deprecated, use `getproperty(f, x)` instead.
│   caller = top-level scope at In[21]:2
└ @ Core In[21]:2
┌ Warning: `getindex(o::PyObject, s::Symbol)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o.s` instead of `o[:s]`.
│   caller = top-level scope at In[21]:3
└ @ Core In[21]:3


(-0.0, 1.5)

In [22]:
?quiver  # queremos averiguar lo que hace quiver

search: quiver quiverkey




Plot a 2-D field of arrows.

Call signatures::

  quiver(U, V, **kw)
  quiver(U, V, C, **kw)
  quiver(X, Y, U, V, **kw)
  quiver(X, Y, U, V, C, **kw)

*U* and *V* are the arrow data, *X* and *Y* set the location of the
arrows, and *C* sets the color of the arrows. These arguments may be 1-D or
2-D arrays or sequences.

If *X* and *Y* are absent, they will be generated as a uniform grid.
If *U* and *V* are 2-D arrays and *X* and *Y* are 1-D, and if ``len(X)`` and
``len(Y)`` match the column and row dimensions of *U*, then *X* and *Y* will be
expanded with :func:`numpy.meshgrid`.

The default settings auto-scales the length of the arrows to a reasonable size.
To change this behavior see the *scale* and *scale_units* kwargs.

The defaults give a slightly swept-back arrow; to make the head a
triangle, make *headaxislength* the same as *headlength*. To make the
arrow more pointed, reduce *headwidth* or increase *headlength* and
*headaxislength*. To make the head smaller relative to the sha