## Ejemplo de Graficación de Vectores en 3-D
### Mecánica de Sólidos
### R. Zúñiga  

In [1]:
# Plotting a 3D vector from https://discourse.julialang.org/t/plot-3d-vector-field/2117/2
# Pkg.add("PyPlot")
ENV["PYTHON"] = ""  

""

In [2]:
using PyPlot

In [3]:
pygui(true)  # si se pone verdadero (true) se grafica en una ventana externa con GUIS y se puede rotar, 
             # falso (false) pone la gráfica en una línea siguiente

true

In [4]:
fig = figure()
#ax = fig[:gca]

N = 10
x,y,z,u,v,w = [randn(N) for i in 1:6];  # creamos 10 vectores aleatorios
#z = z/4


6-element Vector{Vector{Float64}}:
 [0.7352684338492466, 0.4663858412446494, -0.13964738364741072, -0.2673891435796051, -1.0737183725242678, -1.223391550923606, -1.3463448049162188, 0.5630348754998495, 0.7533516213047132, -1.8183801030409175]
 [0.9910781400507062, -0.39696454325873537, -0.0028587816552655917, -0.49096148502342846, -0.8393474600373056, 0.8643456337322127, -0.5049073667111712, -0.12415862818156113, 2.018969558846294, -1.2841687616281625]
 [0.18836817178930607, -0.9694797011390363, -0.5639210326381534, -0.8560599614067307, -0.6492064842635065, 0.21070628086430424, 0.258750906196838, -1.5321899771069893, 0.15697037442549386, 1.2704772913974394]
 [-0.057373324389902294, 2.072304455430878, 1.406465439333949, 0.04532783578427021, -0.8878207554411974, 0.06881035355403314, 0.0078103733879956025, 0.039530946073639654, 1.0262066365933677, 0.5684277931844081]
 [-0.13853896820557454, -1.2271058807223536, -1.1065604666543263, -0.17948773429138598, 0.45554565325771285, -1.27957407001

In [5]:
#ax[:quiver](x,y,z, u,v, w, lw =1.5)
  
xlim([-3.0, 3.0])
ylim([-3.0, 3.0])
zlim([-3.0, 3.0])

quiver(x,y,z, u,v, w, lw =0.5) # grafica los vectores en 3D, los ejes se pueden rotar interactivamente.

# si no funciona se puede usar
#ax[:set_xlim]([0,3])
#ax[:set_ylim]([0,3])
#ax[:set_zlim]([0,3])

/Users/ramon/.julia/conda/3/lib/python3.7/site-packages/matplotlib/pyplot.py:935: UserWarning: Requested projection is different from current axis projection, creating new axis with requested projection.
  return gcf().gca(**kwargs)
/Users/ramon/.julia/conda/3/lib/python3.7/site-packages/matplotlib/figure.py:98: MatplotlibDeprecationWarning: 
Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  "Adding an axes using the same arguments as a previous axes "


PyObject <mpl_toolkits.mplot3d.art3d.Line3DCollection object at 0x7fe8a13c87b8>

In [6]:
x

10-element Vector{Float64}:
  0.7352684338492466
  0.4663858412446494
 -0.13964738364741072
 -0.2673891435796051
 -1.0737183725242678
 -1.223391550923606
 -1.3463448049162188
  0.5630348754998495
  0.7533516213047132
 -1.8183801030409175

In [7]:
y

10-element Vector{Float64}:
  0.9910781400507062
 -0.39696454325873537
 -0.0028587816552655917
 -0.49096148502342846
 -0.8393474600373056
  0.8643456337322127
 -0.5049073667111712
 -0.12415862818156113
  2.018969558846294
 -1.2841687616281625

In [8]:
w

10-element Vector{Float64}:
  0.6086200907896464
  2.451350790728736
 -0.09731271754880964
 -2.7751047856685385
  0.4623753041798434
 -1.7237736839887599
 -0.33567687481513764
  1.6055835831237757
  1.6149764449125759
 -1.0265095837778697

### Graficando vectores unitarios

In [9]:
x = [0;0;0]; y = [0;0;0]; z = [0;0;0]; u = [1;0;0]; v = [0;1;0]; w = [0;0;1]; 

In [10]:
fig = figure()
ax = fig[:gca](projection="3d")
ax[:quiver](x,y,z, u,v, w) # otra forma de llama quiver
xlim([-0.0, 1.5])
ylim([-0.0, 1.5])
zlim([-0.0, 1.5])

(-0.0, 1.5)

In [11]:
?quiver  # queremos averiguar lo que hace quiver

search: quiver quiverkey




Plot a 2-D field of arrows.

Call signatures::

  quiver(U, V, **kw)
  quiver(U, V, C, **kw)
  quiver(X, Y, U, V, **kw)
  quiver(X, Y, U, V, C, **kw)

*U* and *V* are the arrow data, *X* and *Y* set the location of the
arrows, and *C* sets the color of the arrows. These arguments may be 1-D or
2-D arrays or sequences.

If *X* and *Y* are absent, they will be generated as a uniform grid.
If *U* and *V* are 2-D arrays and *X* and *Y* are 1-D, and if ``len(X)`` and
``len(Y)`` match the column and row dimensions of *U*, then *X* and *Y* will be
expanded with :func:`numpy.meshgrid`.

The default settings auto-scales the length of the arrows to a reasonable size.
To change this behavior see the *scale* and *scale_units* kwargs.

The defaults give a slightly swept-back arrow; to make the head a
triangle, make *headaxislength* the same as *headlength*. To make the
arrow more pointed, reduce *headwidth* or increase *headlength* and
*headaxislength*. To make the head smaller relative to the sha